
\begin{align*}
    \sum_{t=t_0}^{t_k} Z_{i,t} \leq \tau \forall i \in V_0 \label{Eq.3}  \\
    0 \leq y_{i,t}^P \leq Q \label{Eq.4} %% 
    \\\dot{a},\breve{a},\widehat{a},
    0 \leq y_{i,t}^D \leq Q \label{Eq.5} %% 
    \\ 
\end{align*}

\begin{gather}
    \sum_{t=t_0}^{t_k} Z_{i,t} \leq \tau \forall i \in V_0 \label{Eq.3}
    \\
    0 \leq y_{i,t}^P \leq min(Q_h, s_i^t) \label{Eq.4} %% 拾取数目的上下限
    \\
    0 \leq y_{i,t}^D \leq min(Q_h, c_i-s_i^t) \label{Eq.5} %% 卸载数目的上下限
    \\\dotplus, * \ast, \boxminus, \ominus, \circledcirc, \bigodot
\end{gather}



\begin{align*}
    \sum_{t=t_0}^{t_k} Z_{i,t} \leq \tau \forall i \in V_0 
    \\
    0 \leq y_{i,t}^P \leq Q 
    \\
    0 \leq y_{i,t}^D \leq Q 
    \\\biguplus, \nsupseteqq, \supsetneq, \Subset
\end{align*}



%split环境（用$对齐）(一个公式分为多行排版)
\begin{equation}
	\begin{split}
	\cos 2x &= \cos^2 x - \sin, \overset{\underset{\mathrm{def}}{}}{=}^2 x\\
	        &= 2\cos^2 x - 1, \simeq, \backsimeq,\not\ll \nleqq,,
	\end{split}
\end{equation}



\begin{align}   
\left\{    \blacksquare\bigtriangleup\blacktriangleright
	\begin{aligned} \ldots \cdots \clubsuit \between
	x&=eq1\\\bigvee \not\operatorname{R}
	y&=eq2+, \Lleftarrow1, \Longleftarrow\rightharpoondown
	\end{aligned}
\right.
%
\end{align}





